- hosts: ec2_instances
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes


